### ISSUE TITLE
JSON result was not a dictionary or list with 0th element a dictionary

### ISSUE THREAD

**Issue by CaliskanHasan** [besanur/homeassistant-addons#23]
Selamün aleyküm...

Bir kac günden beri "PrayerTimes" uygulamasi calismiyor. Hata olarak "JSON result was not a dictionary or list with 0th element a dictionary" gösteriyor.

Lütfen bu probleme bakarmisin ?

Logger: homeassistant.components.rest.sensor
Source: components/rest/sensor.py:161
Integration: RESTful (documentation, issues)
First occurred: 11:17:11 (5 occurrences)
Last logged: 11:24:59

JSON result was not a dictionary or list with 0th element a dictionary

**Comment by besanur** [comment]
Aleykümselam..

Kusura bakma bana bildiri gelmedi..

bendede iki gündür hata vermeye basladi simdi hatayi düzeltmeye calisiyordum bu issue gördüm..

diyanet sayfasinda hicri tarih ekledigi icin hata vermeye basladi simdi düzeltiyorum insallah. sorun devam ederse bildirirsin bana

**Comment by CaliskanHasan** [comment]
Allah razi olsun. Düzeltikten sonra haber verirsen super olur 👍🏼

**Comment by CaliskanHasan** [comment]
Yok olmadi, hala ayni hatayi gösteriyor :/

**Comment by besanur** [comment]
ich denke du verstehst auch deutsch oder weil in deinem Profil Germany steht

**Comment by CaliskanHasan** [comment]
Ja,, bin aus Deutschland :)

**Comment by CaliskanHasan** [comment]
Hab geupdated, aber bekomme immer noch die Fehlermeldung wie oben beschrieben... Helfen dir die Logs aus dem Protokoll weiter ?

**Comment by besanur** [comment]
ok super umso einfacher :)

also soweit ich verstehe liegt das Problem an deiner Home assistant sensor configuration.. vergleich bitte ob du es genau so wie im example ordner gemacht hast

- um sicher zu gehen dass dein addon funktioniert ruf bitte mal den addon endpunkt im Browser auf mit der IP wo dein addon läuft also statt localhost die IP (http://localhost:1453/api/dailyPrayerTimes/<your_region_id>) und dann mit der region id die du haben willst.. es sollten gebetszeiten angezeigt werden.

**Comment by CaliskanHasan** [comment]
Ok... Mit der kopie aus dem Example Ordner scheint es zu funktionieren... Ich schaue nochmal genau was in meinem Sensor anders ist. Ich danke dir für deine mühen 👍🏼 

Tekrar Allah razi olsun und simdiden Bayramin mübarek olsun :)
