### ISSUE TITLE
Can't parse

### ISSUE THREAD

**Issue by hamsi28** [besanur/homeassistant-addons#38]
2023-10-06 08:15:24.519 ERROR 7 --- [nio-1453-exec-6] c.b.p.service.PrayerTimesService         : Can't parse prayer times from server.

After core and system update of home assistant update..

**Comment by besanur** [comment]
I'm working on the error, hopefully I'll fix it in the near future

**Comment by besanur** [comment]
I'm working on the error, hopefully I'll fix it in the near future

**Comment by hamsi28** [comment]
Thank you sooo much.
